language: php

php:
  - 7.2
  - 7.4

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.3
      env: CHECKS=1 DEFAULT=0

  fast_finish: true

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - if [[ $CHECKS == 1 ]]; then composer stan ; fi
  - composer cs-check

notifications:
  email: false
